-- creating users
CREATE TABLE IF NOT EXISTS users (
	id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- creating todos
CREATE TABLE IF NOT EXISTS todos (
    user_id BIGINT NOT NULL,
    id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
	PRIMARY KEY(user_id, id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- creating refresh tokens
CREATE TABLE IF NOT EXISTS refresh_tokens (
	user_id BIGINT NOT NULL,
	token_hash VARCHAR(64),
	expires_at BIGINT,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
